---
- name: "[Elixir] Install elixir packages"
  homebrew: name={{item}} state=latest
  with_items:
    - elixir

- name: "[Elixir] Install hex"
  command: mix local.hex --force

- name: "[Elixir] Install Phoenix"
  command: mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez --force
