---
- name: "[Golang] Install golang"
  homebrew: name={{item}} state=latest
  with_items:
    - go
    - gobject-introspection
    - glide


- name: "[Golang] Make go src directory"
  file: path={{ home_dir }}/.go state=directory

- name: "[Golang] Install Helpful Go Packages"
  command: go get "{{ item }}"
  with_items:
    - golang.org/x/tools/cmd/goimports
    - github.com/motemen/gore
    - github.com/onsi/ginkgo/ginkgo
