---

- hosts: localhost
  connection: local

  vars:
    - superlimic_config_repo: https://github.com/madpilot/superlumic-config.git
    - user_name: myles
    - computername: myles-macbookpro
    - home_dir: "/Users/{{ user_name }}/"
    - user_email: myles@madpilot.com.au
    - github_user_name: madpilot
    - git_user_name: Myles Eftos
    - git_user_email: "{{ user_email }}"
    - git_signing_key: A199061400C9C8B0
    - apple_id_email: myles@madpilot.com.au
    - project_dir: "{{ home_dir }}/Projects/"
    - settings_export_dir: "{{ home_dir }}/tmp/SettingsExports"
    # Set these in secrets file:
    # github_auth_token
    # apple_id_password 

  roles:
    - { role: profile-all, tags: base }
    - { role: profile-developer, tags: base-dev }
    - { role: docker, tags: docker }
  
  tasks:
    - name: Download dotfiles
      git: repo=git@github.com:madpilot/dotfiles.git
           dest="{{ home_dir }}.dotfiles"
           update=yes

    - name: Setup dotfiles
      command: "cd {{ home_dir}}.dotfiles && setup.sh"

    - name: homebrew taps
      homebrew_tap: tap={{ item }} state=present
      with_items:
        - Caskroom/cask

    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - adobe-creative-cloud
        - alfred
        - bettertouchtool
        - blender
        - fluid
        - firefox
        - handbrake
        - microsoft-office
        - quickcal
        - sonos
        - spectacle
        - spotify
        - vmware-fusion
        - whatsapp
#        - yubikey-personalization-gui
#        - yubiswitch
#        - yubikey-neo-manager
#        - yubikey-piv-manager

    - name: install personal brew applications
      homebrew: name={{item}} state=latest
      with_items:
        - mas
        - wireshark

    - name: "[App Store] See which apps are already installed"
      command: bash -c "mas list | cut -f 1 -d ' '"
      register: mas_list

    - name: "[App Store] Install Mac App Store applications"
      command: mas install {{ item.id }}
      when: item.id not in mas_list.stdout_lines
      with_items:
        - { id: "406056744", name: "Evernote" } 
        - { id: "409183694", name: "Keynote" }
        - { id: "405399194", name: "Kindle" }
        - { id: "408981381", name: "iPhoto" }
        - { id: "407963104", name: "Pixelmator" }
        - { id: "409203825", name: "Numbers" }
        - { id: "497799835", name: "Xcode" }
        - { id: "402477606", name: "Sceenium" }
        - { id: "409201541", name: "Pages" }
        - { id: "408981434", name: "iMovie" }
        - { id: "404010395", name: "TextWrangler" }
        - { id: "1176895641", name: "Spark" }
        - { id: "557168941", name: "Tweetbot" }
        - { id: "402390998", name: "Linkinus" }

    - name: "[Spectacle] Setup Settings"
      file: path="{{ home_dir }}/Library/Application Support/Spectacle" state=directory

    - name: "[Spectacle] Copy Settings"
      copy: src="files/Spectacle/Shortcuts.json"
            dest="{{ home_dir }}/Library/Application Support/Spectacle/Shortcuts.json"
