- name: "[Developer] Install developer brew applications"
  homebrew: name={{item}} state=latest
  with_items:
    - awscli
    - bash-completion
    - binutils
    - curl
    - dos2unix
    - direnv
    - httpie
    - jq
    - ncftp
    - phantomjs
    - pwgen
    - rsync
    - tmux
    - unrar
    - wakeonlan
    - watch
    - wget

- name: "[Developer] Install developer cask applications"
  homebrew_cask: name={{item}} state=present
  with_items:
    - charles
    - dash
    - gpgtools
    - iterm2
    - psequel

- name: Write out gitconfig
  template: src=gitconfig.j2 dest={{ home_dir }}/.gitconfig

- name: Write out .bash_profile.local
  copy: src="files/bash_profile.local"
        dest="{{ home_dir }}/.bash_profile.local"

- name: "[Developer] Install completions"
  homebrew: name={{item}} state=latest
  with_items:
    - docker-compose-completion
    - gem-completion
    - mix-completion
    - rails-completion
    - rake-completion
    - ruby-completion
    - bundler-completion
