- name: "[Developer] Install developer brew applications"
  homebrew: name={{item}} state=latest
  with_items:
    - awscli
    - bash-completion
    - binutils
    - curl
    - curl-ca-bundle
    - dos2unix
    - direnv
    - httpie
    - jq
    - ncftp
    - phantomjs
    - pwgen
    - rsync
    - tmux
    - unrar
    - wakeonlan
    - watch
    - wget

- name: "[Developer] Install developer cask applications"
  homebrew_cask: name={{item}} state=present
  with_items:
    - gpgtools
    - dash
    - iterm2

- name: Write out gitconfig
  template: src=gitconfig.j2 dest={{ home_dir }}/.gitconfig
